go

CREATE TABLE CUSTOMERS
(
    CUSTOMERID NVARCHAR(10) PRIMARY KEY,
    FIRSTNAME NVARCHAR(50),
    LASTNAME NVARCHAR(50),
    EMAIL NVARCHAR(50),
    HOUSENO NVARCHAR(50),
    STREET NVARCHAR(50),
    TOWN NVARCHAR(50),
    POSTCODE NVARCHAR(10)
);
go
CREATE TABLE PRODUCTS
(
PRODUCTID INT IDENTITY PRIMARY KEY,
PRODUCTNAME NVARCHAR(50),
COLOUR NVARCHAR(20),
SIZE NVARCHAR(20)
);

go

CREATE TABLE ORDERS
(
ORDERID INT IDENTITY PRIMARY KEY,
CUSTOMERID nvarchar(50),
ORDERDATE DATE,
DELIVERYEXPECTED DATE,
CONTAINSGIFT BIT,
);
go
CREATE TABLE ORDERITEMS
(
ORDERITEMID INT IDENTITY PRIMARY KEY,
ORDERID INT FOREIGN KEY REFERENCES orders,
PRODUCTID INT FOREIGN KEY REFERENCES products,
QUANTITY INT,
PRICE DECIMAL(9,2),
);
go